#!/usr/bin/ash

run_hook() {
    if [ -e /sys/devices/platform/bootsplash.0/enabled ]; then
        echo 0 > /sys/devices/platform/bootsplash.0/enabled
    fi

    DEVICE=$(echo "$root" | sed 's/..$//')
    echo "The current storage device is $DEVICE"

    ROOTFS_FILESYSTYPE=$(fsck -N "$root")

    case "${ROOTFS_FILESYSTYPE}" in
        *fsck.f2fs*) FSRESIZER="/usr/sbin/resize.f2fs";;
        *fsck.ext*) FSRESIZER="/usr/sbin/resize2fs -f";;
    esac

    echo "- + - -" | sfdisk -N 2 "${DEVICE}"

    partx -u "${DEVICE}"
    $FSRESIZER "${DEVICE}p2"

    if [ -e /sys/devices/platform/bootsplash.0/enabled ]; then
        echo 1 > /sys/devices/platform/bootsplash.0/enabled
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
